/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IReNftInterface extends ethers.utils.Interface {
  functions: {
    "claimCollateral(address[],uint256[],uint256[],uint256[])": FunctionFragment;
    "lend(address[],uint256[],uint256[],uint8[],bytes4[],bytes4[],uint8[])": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "rent(address[],uint256[],uint256[],uint256[],uint8[])": FunctionFragment;
    "returnIt(address[],uint256[],uint256[],uint256[])": FunctionFragment;
    "stopLending(address[],uint256[],uint256[],uint256[])": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimCollateral",
    values: [string[], BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "lend",
    values: [
      string[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[],
      BytesLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rent",
    values: [
      string[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "returnIt",
    values: [string[], BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "stopLending",
    values: [string[], BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "returnIt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stopLending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "CollateralClaimed(uint256,uint32)": EventFragment;
    "LendingStopped(uint256,uint32)": EventFragment;
    "Lent(address,uint256,uint8,uint256,address,uint8,bytes4,bytes4,bool,uint8)": EventFragment;
    "Rented(uint256,address,uint8,uint32)": EventFragment;
    "Returned(uint256,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollateralClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LendingStopped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Lent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rented"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Returned"): EventFragment;
}

export class IReNft extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IReNftInterface;

  functions: {
    claimCollateral(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "claimCollateral(address[],uint256[],uint256[],uint256[])"(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lend(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "lend(address[],uint256[],uint256[],uint8[],bytes4[],bytes4[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rent(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "rent(address[],uint256[],uint256[],uint256[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    returnIt(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "returnIt(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopLending(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "stopLending(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  claimCollateral(
    _nfts: string[],
    _tokenIds: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "claimCollateral(address[],uint256[],uint256[],uint256[])"(
    _nfts: string[],
    _tokenIds: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lend(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _maxRentDuration: BigNumberish[],
    _dailyRentPrice: BytesLike[],
    _nftPrice: BytesLike[],
    _paymentToken: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "lend(address[],uint256[],uint256[],uint8[],bytes4[],bytes4[],uint8[])"(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _maxRentDuration: BigNumberish[],
    _dailyRentPrice: BytesLike[],
    _nftPrice: BytesLike[],
    _paymentToken: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155BatchReceived(
    operator: string,
    from: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
    operator: string,
    from: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    operator: string,
    from: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onERC1155Received(address,address,uint256,uint256,bytes)"(
    operator: string,
    from: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC721Received(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rent(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    _rentDurations: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "rent(address[],uint256[],uint256[],uint256[],uint8[])"(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    _rentDurations: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  returnIt(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "returnIt(address[],uint256[],uint256[],uint256[])"(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopLending(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "stopLending(address[],uint256[],uint256[],uint256[])"(
    _nft: string[],
    _tokenId: BigNumberish[],
    _lendAmounts: BigNumberish[],
    _lendingIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    claimCollateral(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "claimCollateral(address[],uint256[],uint256[],uint256[])"(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    lend(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "lend(address[],uint256[],uint256[],uint8[],bytes4[],bytes4[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    rent(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "rent(address[],uint256[],uint256[],uint256[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    returnIt(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "returnIt(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    stopLending(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "stopLending(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    CollateralClaimed(
      lendingId: BigNumberish | null,
      claimedAt: null
    ): TypedEventFilter<
      [BigNumber, number],
      { lendingId: BigNumber; claimedAt: number }
    >;

    LendingStopped(
      lendingId: BigNumberish | null,
      stoppedAt: null
    ): TypedEventFilter<
      [BigNumber, number],
      { lendingId: BigNumber; stoppedAt: number }
    >;

    Lent(
      nftAddress: string | null,
      tokenId: BigNumberish | null,
      lentAmount: null,
      lendingId: null,
      lenderAddress: string | null,
      maxRentDuration: null,
      dailyRentPrice: null,
      nftPrice: null,
      isERC721: null,
      paymentToken: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        number,
        BigNumber,
        string,
        number,
        string,
        string,
        boolean,
        number
      ],
      {
        nftAddress: string;
        tokenId: BigNumber;
        lentAmount: number;
        lendingId: BigNumber;
        lenderAddress: string;
        maxRentDuration: number;
        dailyRentPrice: string;
        nftPrice: string;
        isERC721: boolean;
        paymentToken: number;
      }
    >;

    Rented(
      lendingId: null,
      renterAddress: string | null,
      rentDuration: null,
      rentedAt: null
    ): TypedEventFilter<
      [BigNumber, string, number, number],
      {
        lendingId: BigNumber;
        renterAddress: string;
        rentDuration: number;
        rentedAt: number;
      }
    >;

    Returned(
      lendingId: BigNumberish | null,
      returnedAt: null
    ): TypedEventFilter<
      [BigNumber, number],
      { lendingId: BigNumber; returnedAt: number }
    >;
  };

  estimateGas: {
    claimCollateral(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "claimCollateral(address[],uint256[],uint256[],uint256[])"(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lend(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "lend(address[],uint256[],uint256[],uint8[],bytes4[],bytes4[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rent(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "rent(address[],uint256[],uint256[],uint256[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    returnIt(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "returnIt(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopLending(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "stopLending(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimCollateral(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "claimCollateral(address[],uint256[],uint256[],uint256[])"(
      _nfts: string[],
      _tokenIds: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lend(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "lend(address[],uint256[],uint256[],uint8[],bytes4[],bytes4[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _maxRentDuration: BigNumberish[],
      _dailyRentPrice: BytesLike[],
      _nftPrice: BytesLike[],
      _paymentToken: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onERC1155Received(address,address,uint256,uint256,bytes)"(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rent(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "rent(address[],uint256[],uint256[],uint256[],uint8[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      _rentDurations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    returnIt(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "returnIt(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopLending(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "stopLending(address[],uint256[],uint256[],uint256[])"(
      _nft: string[],
      _tokenId: BigNumberish[],
      _lendAmounts: BigNumberish[],
      _lendingIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
