/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface UtilsInterface extends ethers.utils.Interface {
  functions: {
    "unpackPrice(bytes4,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "unpackPrice",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "unpackPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class Utils extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UtilsInterface;

  functions: {
    unpackPrice(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "unpackPrice(bytes4,uint256)"(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  unpackPrice(
    _price: BytesLike,
    _scale: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "unpackPrice(bytes4,uint256)"(
    _price: BytesLike,
    _scale: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    unpackPrice(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "unpackPrice(bytes4,uint256)"(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    unpackPrice(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "unpackPrice(bytes4,uint256)"(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    unpackPrice(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "unpackPrice(bytes4,uint256)"(
      _price: BytesLike,
      _scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
