/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IReNft } from "../IReNft";

export class IReNft__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IReNft {
    return new Contract(address, _abi, signerOrProvider) as IReNft;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "claimedAt",
        type: "uint32",
      },
    ],
    name: "CollateralClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "stoppedAt",
        type: "uint32",
      },
    ],
    name: "LendingStopped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "nftAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "lentAmount",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lenderAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "maxRentDuration",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "dailyRentPrice",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "nftPrice",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isERC721",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "enum IResolver.PaymentToken",
        name: "paymentToken",
        type: "uint8",
      },
    ],
    name: "Lent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "renterAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "rentDuration",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "rentedAt",
        type: "uint32",
      },
    ],
    name: "Rented",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "lendingId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "returnedAt",
        type: "uint32",
      },
    ],
    name: "Returned",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_nfts",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lentAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lendingIds",
        type: "uint256[]",
      },
    ],
    name: "claimCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_nft",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lendAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint8[]",
        name: "_maxRentDuration",
        type: "uint8[]",
      },
      {
        internalType: "bytes4[]",
        name: "_dailyRentPrice",
        type: "bytes4[]",
      },
      {
        internalType: "bytes4[]",
        name: "_nftPrice",
        type: "bytes4[]",
      },
      {
        internalType: "enum IResolver.PaymentToken[]",
        name: "_paymentToken",
        type: "uint8[]",
      },
    ],
    name: "lend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC1155BatchReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC1155Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_nft",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lentAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lendingIds",
        type: "uint256[]",
      },
      {
        internalType: "uint8[]",
        name: "_rentDurations",
        type: "uint8[]",
      },
    ],
    name: "rent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_nft",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lentAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lendingIds",
        type: "uint256[]",
      },
    ],
    name: "returnIt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_nft",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lentAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_lendingIds",
        type: "uint256[]",
      },
    ],
    name: "stopLending",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
