/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Resolver } from "../Resolver";

export class Resolver__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(_admin: string, overrides?: Overrides): Promise<Resolver> {
    return super.deploy(_admin, overrides || {}) as Promise<Resolver>;
  }
  getDeployTransaction(
    _admin: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(_admin, overrides || {});
  }
  attach(address: string): Resolver {
    return super.attach(address) as Resolver;
  }
  connect(signer: Signer): Resolver__factory {
    return super.connect(signer) as Resolver__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Resolver {
    return new Contract(address, _abi, signerOrProvider) as Resolver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_admin",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_pt",
        type: "uint8",
      },
    ],
    name: "getPaymentToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_pt",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_v",
        type: "address",
      },
    ],
    name: "setPaymentToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102da3803806102da83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610082565b600060208284031215610065578081fd5b81516001600160a01b038116811461007b578182fd5b9392505050565b610249806100916000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063321c6aea1461003b578063c6ee427f14610050575b600080fd5b61004e6100493660046101d2565b61007f565b005b61006361005e3660046101b1565b61017e565b6040516001600160a01b03909116815260200160405180910390f35b60ff82166100ae5760405162461bcd60e51b815260206004820152600060248201526044015b60405180910390fd5b60ff82166000908152600160205260409020546001600160a01b0316156101175760405162461bcd60e51b815260206004820152601860248201527f63616e6e6f74207265736574207468652061646472657373000000000000000060448201526064016100a5565b6000546001600160a01b0316331461014b5760405162461bcd60e51b815260206004820152600060248201526044016100a5565b60ff91909116600090815260016020526040902080546001600160a01b0319166001600160a01b03909216919091179055565b60ff81166000908152600160205260409020546001600160a01b03165b919050565b803560ff8116811461019b57600080fd5b6000602082840312156101c2578081fd5b6101cb826101a0565b9392505050565b600080604083850312156101e4578081fd5b6101ed836101a0565b915060208301356001600160a01b0381168114610208578182fd5b80915050925092905056fea2646970667358221220f5c0b2b8cab3b8216d31a95680e46c01fa94919e970d05cb4d5ef2817433205d64736f6c63430008030033";
