/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { providers, Signer, ethers } from "ethers";
import React, { useEffect, useState } from "react";
import Web3Modal, { IProviderOptions } from "web3modal";
import { ReNFT } from "./typechain/ReNFT";
import { ReNFT__factory } from "./typechain/factories/ReNFT__factory";
import { Resolver } from "./typechain/Resolver";
import { Resolver__factory } from "./typechain/factories/Resolver__factory";
import { E1155 } from "./typechain/E1155";
import { E1155__factory } from "./typechain/factories/E1155__factory";
import { DAI } from "./typechain/DAI";
import { DAI__factory } from "./typechain/factories/DAI__factory";
import { E1155B } from "./typechain/E1155B";
import { E1155B__factory } from "./typechain/factories/E1155B__factory";
import { E721 } from "./typechain/E721";
import { E721__factory } from "./typechain/factories/E721__factory";
import { E721B } from "./typechain/E721B";
import { E721B__factory } from "./typechain/factories/E721B__factory";
import { TUSD } from "./typechain/TUSD";
import { TUSD__factory } from "./typechain/factories/TUSD__factory";
import { USDC } from "./typechain/USDC";
import { USDC__factory } from "./typechain/factories/USDC__factory";
import { USDT } from "./typechain/USDT";
import { USDT__factory } from "./typechain/factories/USDT__factory";
import { Utils } from "./typechain/Utils";
import { Utils__factory } from "./typechain/factories/Utils__factory";
import { WETH } from "./typechain/WETH";
import { WETH__factory } from "./typechain/factories/WETH__factory";
import { ERC1155 } from "./typechain/ERC1155";
import { ERC1155__factory } from "./typechain/factories/ERC1155__factory";
import { ERC20 } from "./typechain/ERC20";
import { ERC20__factory } from "./typechain/factories/ERC20__factory";
import { ERC721 } from "./typechain/ERC721";
import { ERC721__factory } from "./typechain/factories/ERC721__factory";

const emptyContract = {
    instance: undefined,
    factory: undefined
};
const defaultProvider: providers.Provider | undefined = undefined;
export const ProviderContext = React.createContext<[providers.Provider | undefined, React.Dispatch<React.SetStateAction<providers.Provider | undefined>>]>([defaultProvider, () => { }]);
const defaultCurrentAddress: string = "";
export const CurrentAddressContext = React.createContext<[string, React.Dispatch<React.SetStateAction<string>>]>([defaultCurrentAddress, () => { }]);
const defaultSigner: Signer | undefined = undefined;
export const SignerContext = React.createContext<[Signer | undefined, React.Dispatch<React.SetStateAction<Signer | undefined>>]>([defaultSigner, () => { }]);
const defaultSymfoniContext: SymfoniContextInterface = {
    currentHardhatProvider: "",
    init: () => { throw Error("Symfoni context not initialized") },
    loading: false,
    messages: [],
    providers: []
};
export const SymfoniContext = React.createContext<SymfoniContextInterface>(defaultSymfoniContext);
export const ReNFTContext = React.createContext<SymfoniReNFT>(emptyContract);
export const ResolverContext = React.createContext<SymfoniResolver>(emptyContract);
export const E1155Context = React.createContext<SymfoniE1155>(emptyContract);
export const DAIContext = React.createContext<SymfoniDAI>(emptyContract);
export const E1155BContext = React.createContext<SymfoniE1155B>(emptyContract);
export const E721Context = React.createContext<SymfoniE721>(emptyContract);
export const E721BContext = React.createContext<SymfoniE721B>(emptyContract);
export const TUSDContext = React.createContext<SymfoniTUSD>(emptyContract);
export const USDCContext = React.createContext<SymfoniUSDC>(emptyContract);
export const USDTContext = React.createContext<SymfoniUSDT>(emptyContract);
export const UtilsContext = React.createContext<SymfoniUtils>(emptyContract);
export const WETHContext = React.createContext<SymfoniWETH>(emptyContract);
export const ERC1155Context = React.createContext<SymfoniERC1155>(emptyContract);
export const ERC20Context = React.createContext<SymfoniERC20>(emptyContract);
export const ERC721Context = React.createContext<SymfoniERC721>(emptyContract);

export interface SymfoniContextInterface {
    init: (provider?: string) => void;
    loading: boolean;
    messages: string[];
    currentHardhatProvider: string;
    providers: string[];
}

export interface SymfoniProps {
    autoInit?: boolean;
    showLoading?: boolean;
    loadingComponent?: React.ReactNode;
}

export interface SymfoniReNFT {
    instance?: ReNFT;
    factory?: ReNFT__factory;
}

export interface SymfoniResolver {
    instance?: Resolver;
    factory?: Resolver__factory;
}

export interface SymfoniE1155 {
    instance?: E1155;
    factory?: E1155__factory;
}

export interface SymfoniDAI {
    instance?: DAI;
    factory?: DAI__factory;
}

export interface SymfoniE1155B {
    instance?: E1155B;
    factory?: E1155B__factory;
}

export interface SymfoniE721 {
    instance?: E721;
    factory?: E721__factory;
}

export interface SymfoniE721B {
    instance?: E721B;
    factory?: E721B__factory;
}

export interface SymfoniTUSD {
    instance?: TUSD;
    factory?: TUSD__factory;
}

export interface SymfoniUSDC {
    instance?: USDC;
    factory?: USDC__factory;
}

export interface SymfoniUSDT {
    instance?: USDT;
    factory?: USDT__factory;
}

export interface SymfoniUtils {
    instance?: Utils;
    factory?: Utils__factory;
}

export interface SymfoniWETH {
    instance?: WETH;
    factory?: WETH__factory;
}

export interface SymfoniERC1155 {
    instance?: ERC1155;
    factory?: ERC1155__factory;
}

export interface SymfoniERC20 {
    instance?: ERC20;
    factory?: ERC20__factory;
}

export interface SymfoniERC721 {
    instance?: ERC721;
    factory?: ERC721__factory;
}

export const Symfoni: React.FC<SymfoniProps> = ({
    showLoading = true,
    autoInit = true,
    ...props
}) => {
    const [initializeCounter, setInitializeCounter] = useState(0);
    const [currentHardhatProvider, setCurrentHardhatProvider] = useState("");
    const [loading, setLoading] = useState(false);
    const [messages, setMessages] = useState<string[]>([]);
    const [signer, setSigner] = useState<Signer | undefined>(defaultSigner);
    const [provider, setProvider] = useState<providers.Provider | undefined>(defaultProvider);
    const [currentAddress, setCurrentAddress] = useState<string>(defaultCurrentAddress);
    const [fallbackProvider] = useState<string | undefined>(undefined);
    const [providerPriority, setProviderPriority] = useState<string[]>(["web3modal", "hardhat"]);
    const [ReNFT, setReNFT] = useState<SymfoniReNFT>(emptyContract);
    const [Resolver, setResolver] = useState<SymfoniResolver>(emptyContract);
    const [E1155, setE1155] = useState<SymfoniE1155>(emptyContract);
    const [DAI, setDAI] = useState<SymfoniDAI>(emptyContract);
    const [E1155B, setE1155B] = useState<SymfoniE1155B>(emptyContract);
    const [E721, setE721] = useState<SymfoniE721>(emptyContract);
    const [E721B, setE721B] = useState<SymfoniE721B>(emptyContract);
    const [TUSD, setTUSD] = useState<SymfoniTUSD>(emptyContract);
    const [USDC, setUSDC] = useState<SymfoniUSDC>(emptyContract);
    const [USDT, setUSDT] = useState<SymfoniUSDT>(emptyContract);
    const [Utils, setUtils] = useState<SymfoniUtils>(emptyContract);
    const [WETH, setWETH] = useState<SymfoniWETH>(emptyContract);
    const [ERC1155, setERC1155] = useState<SymfoniERC1155>(emptyContract);
    const [ERC20, setERC20] = useState<SymfoniERC20>(emptyContract);
    const [ERC721, setERC721] = useState<SymfoniERC721>(emptyContract);
    useEffect(() => {
        if (messages.length > 0)
            console.debug(messages.pop())
    }, [messages])

    const getProvider = async (): Promise<{ provider: providers.Provider, hardhatProviderName: string } | undefined> => {
        let hardhatProviderName = "Not set";
        let _providerPriority = [...providerPriority];
        // Fallback provider
        if (fallbackProvider && autoInit && initializeCounter === 0) {
            if (localStorage.getItem("WEB3_CONNECT_CACHED_PROVIDER") === null) {
                _providerPriority = _providerPriority.sort((a, b) => {
                    return a === fallbackProvider ? -1 : b === fallbackProvider ? 1 : 0;
                })
            }
        }
        const provider = await _providerPriority.reduce(async (maybeProvider: Promise<providers.Provider | undefined>, providerIdentification) => {
            let foundProvider = await maybeProvider
            if (foundProvider) {
                return Promise.resolve(foundProvider)
            }
            else {
                switch (providerIdentification.toLowerCase()) {
                    case "web3modal":
                        try {
                            const provider = await getWeb3ModalProvider()
                            const web3provider = new ethers.providers.Web3Provider(provider);
                            hardhatProviderName = "web3modal";
                            return Promise.resolve(web3provider)
                        } catch (error) {
                            return Promise.resolve(undefined)
                        }
                    case "hardhat":
                        try {
                            const provider = new ethers.providers.JsonRpcProvider({
                                url: "http://localhost:8545",
                            });
                            hardhatProviderName = "hardhat";
                            return Promise.resolve(provider)
                        } catch (error) {
                            return Promise.resolve(undefined)
                        } default:
                        return Promise.resolve(undefined)
                }
            }
        }, Promise.resolve(undefined)) // end reduce
        return provider ? { provider, hardhatProviderName } : undefined
    };
    const getSigner = async (_provider: providers.Provider, hardhatProviderName: string): Promise<Signer | undefined> => {
        switch (hardhatProviderName) {
            case "web3modal":
                const web3provider = _provider as ethers.providers.Web3Provider
                return await web3provider.getSigner()
            case "hardhat":
                return ethers.Wallet.fromMnemonic("chair trip fetch evidence picnic sock first simple appear slow adjust laptop").connect(_provider)
            default:
                return undefined
        }
    };
    const getWeb3ModalProvider = async (): Promise<any> => {
        const providerOptions: IProviderOptions = {

        };
        const web3Modal = new Web3Modal({
            // network: "mainnet",
            cacheProvider: false,
            providerOptions, // required
        });
        return await web3Modal.connect();
    };

    useEffect(() => {
        let subscribed = true
        const doAsync = async () => {
            const finish = (text: string) => {
                setLoading(false)
                setMessages(old => [...old, text])
            }
            const finishWithContracts = (text: string) => {
                setReNFT(getReNFT(_provider, _signer))
                setResolver(getResolver(_provider, _signer))
                setE1155(getE1155(_provider, _signer))
                setDAI(getDAI(_provider, _signer))
                setE1155B(getE1155B(_provider, _signer))
                setE721(getE721(_provider, _signer))
                setE721B(getE721B(_provider, _signer))
                setTUSD(getTUSD(_provider, _signer))
                setUSDC(getUSDC(_provider, _signer))
                setUSDT(getUSDT(_provider, _signer))
                setUtils(getUtils(_provider, _signer))
                setWETH(getWETH(_provider, _signer))
                setERC1155(getERC1155(_provider, _signer))
                setERC20(getERC20(_provider, _signer))
                setERC721(getERC721(_provider, _signer))
                finish(text)
            }
            if (!autoInit && initializeCounter === 0) return finish("Auto init turned off.")
            setLoading(true)
            setMessages(old => [...old, "Initiating Symfoni React"])
            const providerObject = await getProvider() // getProvider can actually return undefined, see issue https://github.com/microsoft/TypeScript/issues/11094

            if (!subscribed || !providerObject) return finish("No provider or signer.")
            const _provider = providerObject.provider
            setProvider(_provider)
            setMessages(old => [...old, "Useing " + providerObject.hardhatProviderName])
            setCurrentHardhatProvider(providerObject.hardhatProviderName)
            const _signer = await getSigner(_provider, providerObject.hardhatProviderName);

            if (!subscribed || !_signer) return finishWithContracts("Provider, without signer.")
            setSigner(_signer)
            setMessages(old => [...old, "Useing signer"])
            const address = await _signer.getAddress()

            if (!subscribed || !address) return finishWithContracts("Provider and signer, without address.")
            setCurrentAddress(address)

            return finishWithContracts("Completed Symfoni context initialization.")
        };
        doAsync();
        return () => { subscribed = false }
    }, [initializeCounter])

    const getReNFT = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0xB85942c0D4f93009DBefB438dCB76717592a7762"
        const instance = _signer ? ReNFT__factory.connect(contractAddress, _signer) : ReNFT__factory.connect(contractAddress, _provider)
        const contract: SymfoniReNFT = {
            instance: instance,
            factory: _signer ? new ReNFT__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getResolver = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x13c41354BAEA681f771cD9ff760FD8719dfAc2a3"
        const instance = _signer ? Resolver__factory.connect(contractAddress, _signer) : Resolver__factory.connect(contractAddress, _provider)
        const contract: SymfoniResolver = {
            instance: instance,
            factory: _signer ? new Resolver__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getE1155 = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x853eae7044A2C407A425e5e6e3A9a1998c69f015"
        const instance = _signer ? E1155__factory.connect(contractAddress, _signer) : E1155__factory.connect(contractAddress, _provider)
        const contract: SymfoniE1155 = {
            instance: instance,
            factory: _signer ? new E1155__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getDAI = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0xc0AE2046770183cD98f516E24bF196f30Ab849EB"
        const instance = _signer ? DAI__factory.connect(contractAddress, _signer) : DAI__factory.connect(contractAddress, _provider)
        const contract: SymfoniDAI = {
            instance: instance,
            factory: _signer ? new DAI__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getE1155B = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0xE97B54D59AA4eDEb9d8A017373a146753D7B6496"
        const instance = _signer ? E1155B__factory.connect(contractAddress, _signer) : E1155B__factory.connect(contractAddress, _provider)
        const contract: SymfoniE1155B = {
            instance: instance,
            factory: _signer ? new E1155B__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getE721 = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x6E88A2AA2657a97e8FC71f1C821b0Ec5Fc03801f"
        const instance = _signer ? E721__factory.connect(contractAddress, _signer) : E721__factory.connect(contractAddress, _provider)
        const contract: SymfoniE721 = {
            instance: instance,
            factory: _signer ? new E721__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getE721B = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x5aeB28A14252497E754e72A98F577EEe717d4BD9"
        const instance = _signer ? E721B__factory.connect(contractAddress, _signer) : E721B__factory.connect(contractAddress, _provider)
        const contract: SymfoniE721B = {
            instance: instance,
            factory: _signer ? new E721B__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getTUSD = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x46517180542334083d8aa60A44Da5b4a4a70c259"
        const instance = _signer ? TUSD__factory.connect(contractAddress, _signer) : TUSD__factory.connect(contractAddress, _provider)
        const contract: SymfoniTUSD = {
            instance: instance,
            factory: _signer ? new TUSD__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getUSDC = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x214D0D13F19Ad8Aca2dff8Ded96bb2DFa2835e6C"
        const instance = _signer ? USDC__factory.connect(contractAddress, _signer) : USDC__factory.connect(contractAddress, _provider)
        const contract: SymfoniUSDC = {
            instance: instance,
            factory: _signer ? new USDC__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getUSDT = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x0Abc973E504E242d8609685E69Ea96b4e3621d85"
        const instance = _signer ? USDT__factory.connect(contractAddress, _signer) : USDT__factory.connect(contractAddress, _provider)
        const contract: SymfoniUSDT = {
            instance: instance,
            factory: _signer ? new USDT__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getUtils = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0x3460b0d63Be513ebe056dC8510BaC47Cc10EF270"
        const instance = _signer ? Utils__factory.connect(contractAddress, _signer) : Utils__factory.connect(contractAddress, _provider)
        const contract: SymfoniUtils = {
            instance: instance,
            factory: _signer ? new Utils__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getWETH = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = "0xD7C6a8bB6d1FA43d1e020057d61880e2A36f67fb"
        const instance = _signer ? WETH__factory.connect(contractAddress, _signer) : WETH__factory.connect(contractAddress, _provider)
        const contract: SymfoniWETH = {
            instance: instance,
            factory: _signer ? new WETH__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getERC1155 = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? ERC1155__factory.connect(ethers.constants.AddressZero, _signer) : ERC1155__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniERC1155 = {
            instance: instance,
            factory: _signer ? new ERC1155__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getERC20 = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? ERC20__factory.connect(ethers.constants.AddressZero, _signer) : ERC20__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniERC20 = {
            instance: instance,
            factory: _signer ? new ERC20__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getERC721 = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? ERC721__factory.connect(ethers.constants.AddressZero, _signer) : ERC721__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniERC721 = {
            instance: instance,
            factory: _signer ? new ERC721__factory(_signer) : undefined,
        }
        return contract
    }
        ;

    const handleInitProvider = (provider?: string) => {
        if (provider) {
            setProviderPriority(old => old.sort((a, b) => {
                return a === provider ? -1 : b === provider ? 1 : 0;
            }))
        }
        setInitializeCounter(initializeCounter + 1)
    }
    return (
        <SymfoniContext.Provider value={{ init: (provider) => handleInitProvider(provider), providers: providerPriority, currentHardhatProvider, loading, messages }}>
            <ProviderContext.Provider value={[provider, setProvider]}>
                <SignerContext.Provider value={[signer, setSigner]}>
                    <CurrentAddressContext.Provider value={[currentAddress, setCurrentAddress]}>
                        <ReNFTContext.Provider value={ReNFT}>
                            <ResolverContext.Provider value={Resolver}>
                                <E1155Context.Provider value={E1155}>
                                    <DAIContext.Provider value={DAI}>
                                        <E1155BContext.Provider value={E1155B}>
                                            <E721Context.Provider value={E721}>
                                                <E721BContext.Provider value={E721B}>
                                                    <TUSDContext.Provider value={TUSD}>
                                                        <USDCContext.Provider value={USDC}>
                                                            <USDTContext.Provider value={USDT}>
                                                                <UtilsContext.Provider value={Utils}>
                                                                    <WETHContext.Provider value={WETH}>
                                                                        <ERC1155Context.Provider value={ERC1155}>
                                                                            <ERC20Context.Provider value={ERC20}>
                                                                                <ERC721Context.Provider value={ERC721}>
                                                                                    {showLoading && loading ?
                                                                                        props.loadingComponent
                                                                                            ? props.loadingComponent
                                                                                            : <div>
                                                                                                {messages.map((msg, i) => (
                                                                                                    <p key={i}>{msg}</p>
                                                                                                ))}
                                                                                            </div>
                                                                                        : props.children
                                                                                    }
                                                                                </ERC721Context.Provider >
                                                                            </ERC20Context.Provider >
                                                                        </ERC1155Context.Provider >
                                                                    </WETHContext.Provider >
                                                                </UtilsContext.Provider >
                                                            </USDTContext.Provider >
                                                        </USDCContext.Provider >
                                                    </TUSDContext.Provider >
                                                </E721BContext.Provider >
                                            </E721Context.Provider >
                                        </E1155BContext.Provider >
                                    </DAIContext.Provider >
                                </E1155Context.Provider >
                            </ResolverContext.Provider >
                        </ReNFTContext.Provider >
                    </CurrentAddressContext.Provider>
                </SignerContext.Provider>
            </ProviderContext.Provider>
        </SymfoniContext.Provider>
    )

};
